### PR TITLE
fix(mv): correct dst name

### LINKED ISSUE #18: Mv bug
Fix: https://github.com/ipfs/go-ipfs/issues/5346

### PR DESCRIPTION
**Pull request by overbool**
Fix: https://github.com/ipfs/go-mfs/issues/18
Refer to: https://github.com/ipfs/go-ipfs/issues/5346

From https://github.com/ipfs/go-ipfs/pull/5361#discussion_r209113416 the rules should be:

```
if src.Type == dir:
     if dest.Type == dir: 
            if dest.Contains(src):
                if dest.Empty(): unlink
                else: return an error
            move src to dest/
     else if dest.Type == file: case a error
else if src.Type == file:
     if dest.Type == file: replace(src, dest)
     else if desc.Type == directory: 
              if desc.Contains(src):
                  if desc.Type == dir and not desc.Empty():
                      return an error
                  unlink src from desc
              move src to desc/
```

### CODE REVIEW

**Comment by schomatis** [comment]
Is this a port of https://github.com/ipfs/go-ipfs/pull/5361? Has the original author abandoned that effort? Let me do a quick ping there before moving forward here.

**Review by schomatis — CHANGES_REQUESTED** [review]
I'm having some trouble following this code, I don't understand why the source path parsing logic is different than the destination path's. I'd prefer encapsulating that and having a single path pre-processing function using the Go's standard [`Clean`](https://golang.org/pkg/path/#Clean) (instead of the ad hoc `TrimRight` call to remove the slash) and `Split` functions and then apply a logic flow that would follow something like what's described [here](https://github.com/ipfs/go-mfs/pull/19#issue-222960297) (taken from the original PR).

**Comment by Stebalien** [comment]
@schomatis in general, this code is guaranteed to be pretty tricky because we're trying to follow POSIX. That is, `ipfs files cp a b` should behave like `cp a b`. Unfortunately, the `cp` command has a bunch of weird edge-cases.

**Comment by schomatis** [comment]
@Stebalien I agree, my comment was not about the POSIX rules or the pseudo-code that guided this PR but about the implementation.

**Comment by overbool** [comment]
@schomatis sorry for my delay(I have completely forgotten it), I will do it right away.

**Comment by aschmahmann** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo).  In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Boxo (and reference this issue) if resolving this issue is still critical for unblocking or improving your usecase.

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).

**Pull request closed without merging**
